// Country Travel Information for Pakistani Passport Holders
// Comprehensive travel metadata for all 70 countries in PakVisa Advisor

export interface TravelInfo {
  languages: string[];
  dialCode: string;
  plugType: string;
  voltage: string;
  waterSafe: boolean;
  tipping: string;
  halalFood: 'Widely Available' | 'Available' | 'Limited' | 'Not Available';
  transport: string;
  emergencyPolice: string;
  emergencyAmbulance: string;
  emergencyFire: string;
  vaccines: string[];
  pakistaniCommunity: 'Large' | 'Moderate' | 'Small' | 'Very Small';
  internet: string;
  description: string;
}

export const COUNTRY_TRAVEL_INFO: Record<string, TravelInfo> = {
  // ==================== VISA FREE ====================
  Malaysia: {
    languages: ['Malay', 'English', 'Mandarin', 'Tamil'],
    dialCode: '+60',
    plugType: 'Type G',
    voltage: '240V',
    waterSafe: false,
    tipping: 'Not common — service charge usually included',
    halalFood: 'Widely Available',
    transport: 'Grab, LRT, MRT, KTM trains, RapidKL buses',
    emergencyPolice: '999',
    emergencyAmbulance: '999',
    emergencyFire: '994',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Small',
    internet: '4G/5G widely available, free WiFi in malls and KLIA airport',
    description: 'Visa-free tropical paradise with stunning beaches, modern cities, and incredible street food. Kuala Lumpur is a major hub for Pakistani travelers.',
  },
  Azerbaijan: {
    languages: ['Azerbaijani', 'Russian', 'English'],
    dialCode: '+994',
    plugType: 'Type C/F',
    voltage: '220V',
    waterSafe: false,
    tipping: 'Not required, but appreciated (5-10%)',
    halalFood: 'Widely Available',
    transport: 'Uber, Bolt, Baku Metro, buses',
    emergencyPolice: '102',
    emergencyAmbulance: '103',
    emergencyFire: '101',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Small',
    internet: '3G/4G available, WiFi in hotels and cafes in Baku',
    description: 'Visa-free gateway between Europe and Asia. Baku offers stunning architecture, rich culture, and affordable living.',
  },
  HongKong: {
    languages: ['Cantonese', 'English', 'Mandarin'],
    dialCode: '+852',
    plugType: 'Type D/G',
    voltage: '220V',
    waterSafe: false,
    tipping: 'Not expected — 10% service charge usually added',
    halalFood: 'Available',
    transport: 'MTR, buses, trams, Star Ferry',
    emergencyPolice: '999',
    emergencyAmbulance: '999',
    emergencyFire: '999',
    vaccines: [],
    pakistaniCommunity: 'Small',
    internet: '5G and WiFi everywhere, free GovWiFi in public areas',
    description: 'World-class shopping, dining, and skyline views. Pakistani passport holders enjoy visa-free entry for up to 14 days.',
  },
  Maldives: {
    languages: ['Dhivehi', 'English'],
    dialCode: '+960',
    plugType: 'Type A/C/D/G/J/L',
    voltage: '230V',
    waterSafe: true,
    tipping: 'Resorts include service charge; cash tips for staff appreciated',
    halalFood: 'Widely Available',
    transport: 'Speedboats, seaplanes, resort shuttles — limited on local islands',
    emergencyPolice: '119',
    emergencyAmbulance: '102',
    emergencyFire: '118',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Very Small',
    internet: 'Good WiFi at resorts; limited on local islands',
    description: 'Luxury island paradise with crystal-clear waters. An Islamic nation — halal food is standard everywhere.',
  },
  Nepal: {
    languages: ['Nepali', 'English', 'Hindi'],
    dialCode: '+977',
    plugType: 'Type C/D/M',
    voltage: '230V',
    waterSafe: false,
    tipping: 'Not customary in restaurants; tips for guides 10-15%',
    halalFood: 'Available',
    transport: 'Taxis, tempo, microbuses, domestic flights',
    emergencyPolice: '100',
    emergencyAmbulance: '102',
    emergencyFire: '101',
    vaccines: ['Hepatitis A', 'Typhoid', 'Malaria prophylaxis'],
    pakistaniCommunity: 'Moderate',
    internet: '3G/4G in cities, limited in rural areas',
    description: 'Home to Mount Everest and a deeply spiritual culture. Visa-free entry for Pakistani citizens. Great budget destination.',
  },

  // ==================== VISA ON ARRIVAL ====================
  UAE: {
    languages: ['Arabic', 'English', 'Hindi', 'Urdu'],
    dialCode: '+971',
    plugType: 'Type C/D/G',
    voltage: '220V',
    waterSafe: true,
    tipping: '10-15% standard at restaurants',
    halalFood: 'Widely Available',
    transport: 'Dubai Metro, Abu Dhabi buses, Uber, Careem',
    emergencyPolice: '999',
    emergencyAmbulance: '998',
    emergencyFire: '997',
    vaccines: [],
    pakistaniCommunity: 'Large',
    internet: '5G and WiFi everywhere, ultra-fast speeds',
    description: 'Top destination for Pakistani travelers. Dubai and Abu Dhabi offer world-class shopping, dining, and entertainment. Large Pakistani diaspora community.',
  },
  SaudiArabia: {
    languages: ['Arabic', 'English'],
    dialCode: '+966',
    plugType: 'Type A/B/G',
    voltage: '220V',
    waterSafe: true,
    tipping: 'Not expected in most places',
    halalFood: 'Widely Available',
    transport: 'Uber, Careem, SAPTCO buses, Haramain High-Speed Rail',
    emergencyPolice: '911',
    emergencyAmbulance: '997',
    emergencyFire: '998',
    vaccines: ['Meningococcal (required for Hajj/Umrah)'],
    pakistaniCommunity: 'Large',
    internet: 'Good 4G/5G coverage, WiFi in hotels and malls',
    description: 'Spiritual home for Muslims. Apply for e-Visa for tourism and Umrah. Huge Pakistani community — you will feel at home.',
  },
  Bahrain: {
    languages: ['Arabic', 'English'],
    dialCode: '+973',
    plugType: 'Type G',
    voltage: '220V',
    waterSafe: true,
    tipping: 'Not expected; service charge sometimes included',
    halalFood: 'Widely Available',
    transport: 'Uber, Careem, Bahrain buses',
    emergencyPolice: '999',
    emergencyAmbulance: '999',
    emergencyFire: '999',
    vaccines: [],
    pakistaniCommunity: 'Moderate',
    internet: 'Good 4G coverage, WiFi widely available',
    description: 'Small island kingdom known for pearls,Formula 1, and a relaxed atmosphere compared to neighboring Gulf states.',
  },
  Egypt: {
    languages: ['Arabic', 'English'],
    dialCode: '+20',
    plugType: 'Type C/E',
    voltage: '220V',
    waterSafe: false,
    tipping: 'Expected (10-15%); baksheesh culture',
    halalFood: 'Widely Available',
    transport: 'Uber, Careem, Cairo Metro, microbuses',
    emergencyPolice: '122',
    emergencyAmbulance: '123',
    emergencyFire: '180',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Moderate',
    internet: '3G/4G available, WiFi in hotels',
    description: 'Land of the pharaohs with the Pyramids, Nile River, and rich ancient history. Affordable destination with visa on arrival.',
  },
  Indonesia: {
    languages: ['Indonesian', 'English', 'Javanese'],
    dialCode: '+62',
    plugType: 'Type C/F',
    voltage: '230V',
    waterSafe: false,
    tipping: 'Not required; 5-10% at upscale hotels',
    halalFood: 'Widely Available',
    transport: 'Gojek, Grab, TransJakarta buses, commuter trains',
    emergencyPolice: '110',
    emergencyAmbulance: '118',
    emergencyFire: '113',
    vaccines: ['Hepatitis A', 'Typhoid', 'Malaria prophylaxis'],
    pakistaniCommunity: 'Small',
    internet: 'Good 4G coverage in Java/Bali, WiFi in hotels and cafes',
    description: 'World\'s largest Muslim-majority country with 17,000+ islands. Bali, Jakarta, and Lombok are popular spots for Pakistani tourists.',
  },
  Jordan: {
    languages: ['Arabic', 'English'],
    dialCode: '+962',
    plugType: 'Type C/D/F/G/J/L',
    voltage: '230V',
    waterSafe: false,
    tipping: '10% at restaurants; round up taxi fares',
    halalFood: 'Widely Available',
    transport: 'Uber, Careem, local taxis, JETT buses',
    emergencyPolice: '911',
    emergencyAmbulance: '911',
    emergencyFire: '911',
    vaccines: [],
    pakistaniCommunity: 'Moderate',
    internet: 'Good 3G/4G, WiFi in hotels and cafes',
    description: 'Petra, the Dead Sea, and warm hospitality. A must-visit destination rich in history and natural wonders.',
  },
  Oman: {
    languages: ['Arabic', 'English'],
    dialCode: '+968',
    plugType: 'Type C/G',
    voltage: '240V',
    waterSafe: true,
    tipping: 'Not expected; round up taxi fares',
    halalFood: 'Widely Available',
    transport: 'Careem, taxis, Oman National Transport buses',
    emergencyPolice: '9999',
    emergencyAmbulance: '9999',
    emergencyFire: '9999',
    vaccines: [],
    pakistaniCommunity: 'Moderate',
    internet: 'Good coverage in Muscat, limited outside cities',
    description: 'Stunning deserts, wadis, and coastline. A peaceful Gulf state with natural beauty and rich cultural heritage.',
  },
  Qatar: {
    languages: ['Arabic', 'English'],
    dialCode: '+974',
    plugType: 'Type D/G',
    voltage: '240V',
    waterSafe: true,
    tipping: '10-15% at restaurants is appreciated',
    halalFood: 'Widely Available',
    transport: 'Karwa taxis, Uber, Careem, Doha Metro',
    emergencyPolice: '999',
    emergencyAmbulance: '999',
    emergencyFire: '999',
    vaccines: [],
    pakistaniCommunity: 'Moderate',
    internet: 'Excellent 5G, WiFi widely available',
    description: 'World Cup 2022 host with stunning museums, skyline, and cultural attractions. Fast-growing destination.',
  },
  Tanzania: {
    languages: ['Swahili', 'English'],
    dialCode: '+255',
    plugType: 'Type D/G',
    voltage: '230V',
    waterSafe: false,
    tipping: 'Not expected but appreciated (10%)',
    halalFood: 'Available',
    transport: 'Daladala minibuses, Uber/Bolt in Dar es Salaam, domestic flights for Safari',
    emergencyPolice: '112',
    emergencyAmbulance: '115',
    emergencyFire: '114',
    vaccines: ['Hepatitis A', 'Typhoid', 'Yellow Fever', 'Malaria prophylaxis'],
    pakistaniCommunity: 'Small',
    internet: '3G in cities, WiFi in hotels',
    description: 'Serengeti, Mount Kilimanjaro, and Zanzibar beaches. An African adventure destination like no other.',
  },
  Thailand: {
    languages: ['Thai', 'English'],
    dialCode: '+66',
    plugType: 'Type A/B/C',
    voltage: '220V',
    waterSafe: false,
    tipping: 'Not required; 10% at upscale restaurants',
    halalFood: 'Available',
    transport: 'BTS Skytrain, MRT, Grab, tuk-tuks, buses',
    emergencyPolice: '191',
    emergencyAmbulance: '1669',
    emergencyFire: '199',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Small',
    internet: 'Excellent 4G/5G, free WiFi in malls and BTS stations',
    description: 'Bangkok street food, pristine beaches, and Buddhist temples. Visa on arrival for Pakistani passport holders.',
  },

  // ==================== E-VISA ====================
  Turkey: {
    languages: ['Turkish', 'English', 'Kurdish'],
    dialCode: '+90',
    plugType: 'Type C/F',
    voltage: '230V',
    waterSafe: false,
    tipping: '5-10% at restaurants; round up taxi fares',
    halalFood: 'Widely Available',
    transport: 'Metro, trams, Uber, Dolmus (shared taxis), buses, YHT high-speed trains',
    emergencyPolice: '155',
    emergencyAmbulance: '112',
    emergencyFire: '110',
    vaccines: [],
    pakistaniCommunity: 'Large',
    internet: 'Good 4G/5G, WiFi widely available in cities',
    description: 'Istanbul bridges Europe and Asia. Rich Ottoman history, stunning mosques, and popular for Pakistani medical tourism.',
  },
  Cambodia: {
    languages: ['Khmer', 'English'],
    dialCode: '+855',
    plugType: 'Type A/B/C/O',
    voltage: '230V',
    waterSafe: false,
    tipping: 'Not expected; small tips for guides appreciated',
    halalFood: 'Limited',
    transport: 'Tuk-tuks, PassApp, Grab, buses',
    emergencyPolice: '117',
    emergencyAmbulance: '119',
    emergencyFire: '118',
    vaccines: ['Hepatitis A', 'Typhoid', 'Malaria prophylaxis'],
    pakistaniCommunity: 'Very Small',
    internet: '3G/4G in cities, WiFi in hotels',
    description: 'Angkor Wat, affordable living, and a growing tourist destination. Budget-friendly e-Visa available online.',
  },
  Ethiopia: {
    languages: ['Amharic', 'English', 'Oromo'],
    dialCode: '+251',
    plugType: 'Type C/E/F/L',
    voltage: '220V',
    waterSafe: false,
    tipping: 'Not customary; 5-10% at hotels appreciated',
    halalFood: 'Limited',
    transport: 'Blue taxis, minibuses, Ethiopian Airlines domestic flights',
    emergencyPolice: '991',
    emergencyAmbulance: '902',
    emergencyFire: '939',
    vaccines: ['Hepatitis A', 'Typhoid', 'Yellow Fever', 'Malaria prophylaxis'],
    pakistaniCommunity: 'Very Small',
    internet: 'Limited WiFi, growing 4G coverage in Addis Ababa',
    description: 'Ancient Christian heritage, coffee birthplace, and unique culture. e-Visa available for Pakistani citizens.',
  },
  Kenya: {
    languages: ['Swahili', 'English'],
    dialCode: '+254',
    plugType: 'Type G',
    voltage: '240V',
    waterSafe: false,
    tipping: 'Not required; 10% at upscale venues',
    halalFood: 'Available',
    transport: 'Uber, Bolt, matatus (minibuses), buses',
    emergencyPolice: '112',
    emergencyAmbulance: '999',
    emergencyFire: '999',
    vaccines: ['Hepatitis A', 'Typhoid', 'Yellow Fever', 'Malaria prophylaxis'],
    pakistaniCommunity: 'Small',
    internet: 'Good 4G in Nairobi, WiFi in hotels and cafes',
    description: 'Safari capital of Africa. Maasai Mara, Nairobi tech hub, and Mombasa beaches. e-Visa process is straightforward.',
  },
  SriLanka: {
    languages: ['Sinhala', 'Tamil', 'English'],
    dialCode: '+94',
    plugType: 'Type D',
    voltage: '230V',
    waterSafe: false,
    tipping: 'Not mandatory; 10% at restaurants appreciated',
    halalFood: 'Available',
    transport: 'Uber, PickMe, trains, SLTB buses, tuk-tuks',
    emergencyPolice: '119',
    emergencyAmbulance: '110',
    emergencyFire: '111',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Small',
    internet: 'Good 4G, WiFi in hotels and cafes',
    description: 'Tea plantations, ancient temples, and beautiful beaches. Affordable destination with a rich cultural heritage.',
  },
  Armenia: {
    languages: ['Armenian', 'Russian', 'English'],
    dialCode: '+374',
    plugType: 'Type C/F',
    voltage: '230V',
    waterSafe: false,
    tipping: '10% at restaurants is standard',
    halalFood: 'Limited',
    transport: 'Yandex Go, buses, metro in Yerevan',
    emergencyPolice: '102',
    emergencyAmbulance: '103',
    emergencyFire: '101',
    vaccines: [],
    pakistaniCommunity: 'Very Small',
    internet: 'Good 4G coverage, WiFi in Yerevan cafes',
    description: 'Ancient churches, stunning mountains, and warm hospitality. e-Visa available online with quick approval.',
  },
  Georgia: {
    languages: ['Georgian', 'Russian', 'English'],
    dialCode: '+995',
    plugType: 'Type C/F',
    voltage: '220V',
    waterSafe: false,
    tipping: 'Not expected but 10% is appreciated',
    halalFood: 'Available',
    transport: 'Bolt, Yandex Go, metro in Tbilisi, marshrutkas (minibuses)',
    emergencyPolice: '112',
    emergencyAmbulance: '112',
    emergencyFire: '112',
    vaccines: [],
    pakistaniCommunity: 'Small',
    internet: 'Good 3G/4G, free WiFi in Tbilisi public areas',
    description: 'Affordable European country with stunning Caucasus mountains, ancient wine culture, and visa-free entry for some periods.',
  },

  // ==================== EMBASSY REQUIRED ====================
  Afghanistan: {
    languages: ['Dari', 'Pashto'],
    dialCode: '+93',
    plugType: 'Type C/F',
    voltage: '220V',
    waterSafe: false,
    tipping: 'Not customary',
    halalFood: 'Widely Available',
    transport: 'Taxis, shared vans, limited public transport',
    emergencyPolice: '119',
    emergencyAmbulance: '113',
    emergencyFire: '119',
    vaccines: ['Hepatitis A', 'Typhoid', 'Polio booster'],
    pakistaniCommunity: 'Large',
    internet: 'Limited 3G in major cities',
    description: 'Neighboring country with deep cultural ties to Pakistan. Travel requires careful planning and security awareness.',
  },
  Algeria: {
    languages: ['Arabic', 'French', 'Berber'],
    dialCode: '+213',
    plugType: 'Type C/E',
    voltage: '230V',
    waterSafe: false,
    tipping: '10% at restaurants',
    halalFood: 'Widely Available',
    transport: 'Taxis, buses, SNTF trains',
    emergencyPolice: '14',
    emergencyAmbulance: '14',
    emergencyFire: '14',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Very Small',
    internet: '3G/4G in Algiers, WiFi in hotels',
    description: 'North African country with Roman ruins, Sahara desert, and Mediterranean coastline.',
  },
  Australia: {
    languages: ['English'],
    dialCode: '+61',
    plugType: 'Type I',
    voltage: '230V',
    waterSafe: true,
    tipping: 'Not required — 10% for exceptional service',
    halalFood: 'Available',
    transport: 'Uber, trains, buses, trams',
    emergencyPolice: '000',
    emergencyAmbulance: '000',
    emergencyFire: '000',
    vaccines: [],
    pakistaniCommunity: 'Moderate',
    internet: 'Excellent 5G, WiFi widely available',
    description: 'Iconic destination with Great Barrier Reef, Sydney Opera House, and diverse wildlife. Student visa popular for Pakistanis.',
  },
  Austria: {
    languages: ['German', 'English'],
    dialCode: '+43',
    plugType: 'Type C/F',
    voltage: '230V',
    waterSafe: true,
    tipping: '5-10% at restaurants; round up bills',
    halalFood: 'Available',
    transport: 'Vienna U-Bahn, trains (ÖBB), trams, buses',
    emergencyPolice: '133',
    emergencyAmbulance: '144',
    emergencyFire: '122',
    vaccines: [],
    pakistaniCommunity: 'Small',
    internet: 'Excellent coverage, WiFi in public transport',
    description: 'Schengen country with Vienna\'s imperial palaces, Alpine scenery, and classical music heritage.',
  },
  Bangladesh: {
    languages: ['Bengali', 'English'],
    dialCode: '+880',
    plugType: 'Type A/C/D/G',
    voltage: '220V',
    waterSafe: false,
    tipping: 'Not expected',
    halalFood: 'Widely Available',
    transport: 'Uber, Pathao, rickshaws, buses, Bangladesh Railway',
    emergencyPolice: '999',
    emergencyAmbulance: '199',
    emergencyFire: '999',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Moderate',
    internet: '4G available, WiFi in hotels',
    description: 'Neighboring Muslim-majority nation with rich Bengali culture and the Sundarbans mangrove forest.',
  },
  Belgium: {
    languages: ['Dutch', 'French', 'German', 'English'],
    dialCode: '+32',
    plugType: 'Type C/E',
    voltage: '230V',
    waterSafe: true,
    tipping: 'Service charge included; small tip appreciated',
    halalFood: 'Available',
    transport: 'Brussels Metro, trains (SNCB), buses, trams',
    emergencyPolice: '101',
    emergencyAmbulance: '112',
    emergencyFire: '112',
    vaccines: [],
    pakistaniCommunity: 'Moderate',
    internet: 'Excellent coverage, WiFi in many public places',
    description: 'Schengen country — one visa for 27 European nations. Known for chocolates, waffles, and EU institutions in Brussels.',
  },
  Brazil: {
    languages: ['Portuguese', 'English'],
    dialCode: '+55',
    plugType: 'Type C/N',
    voltage: '127V/220V',
    waterSafe: false,
    tipping: '10% at restaurants is standard',
    halalFood: 'Limited',
    transport: 'Uber, 99, metro (major cities), buses',
    emergencyPolice: '190',
    emergencyAmbulance: '192',
    emergencyFire: '193',
    vaccines: ['Hepatitis A', 'Typhoid', 'Yellow Fever'],
    pakistaniCommunity: 'Very Small',
    internet: 'Good 4G in cities, WiFi in hotels',
    description: 'Vibrant South American nation famous for Carnival, Amazon rainforest, and Rio de Janeiro.',
  },
  Canada: {
    languages: ['English', 'French'],
    dialCode: '+1',
    plugType: 'Type A/B',
    voltage: '120V',
    waterSafe: true,
    tipping: '15-20% at restaurants is expected',
    halalFood: 'Available',
    transport: 'Uber, TTC (Toronto), STM (Montreal), VIA Rail',
    emergencyPolice: '911',
    emergencyAmbulance: '911',
    emergencyFire: '911',
    vaccines: [],
    pakistaniCommunity: 'Large',
    internet: 'Excellent 5G, WiFi widely available',
    description: 'Popular immigration and study destination. Large Pakistani diaspora in Toronto, Vancouver, and Montreal.',
  },
  China: {
    languages: ['Mandarin', 'English'],
    dialCode: '+86',
    plugType: 'Type A/C/I',
    voltage: '220V',
    waterSafe: false,
    tipping: 'Not customary and may be refused',
    halalFood: 'Available',
    transport: 'Subway, DiDi, high-speed trains (CRH), buses',
    emergencyPolice: '110',
    emergencyAmbulance: '120',
    emergencyFire: '119',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Small',
    internet: 'Good 4G; note: WhatsApp/Google blocked — use WeChat/VPN',
    description: 'Major trading partner for Pakistan. CPEC corridor. Rich history, modern cities, and diverse cuisine.',
  },
  Denmark: {
    languages: ['Danish', 'English'],
    dialCode: '+45',
    plugType: 'Type C/E/K',
    voltage: '230V',
    waterSafe: true,
    tipping: 'Not expected — service charge included',
    halalFood: 'Available',
    transport: 'S-trains, Metro (Copenhagen), buses, DSB trains',
    emergencyPolice: '112',
    emergencyAmbulance: '112',
    emergencyFire: '112',
    vaccines: [],
    pakistaniCommunity: 'Small',
    internet: 'Excellent coverage, WiFi widely available',
    description: 'Schengen country known for hygge lifestyle, Viking history, and high quality of life.',
  },
  France: {
    languages: ['French', 'English'],
    dialCode: '+33',
    plugType: 'Type C/E',
    voltage: '230V',
    waterSafe: true,
    tipping: 'Service included; 5-10% for exceptional service',
    halalFood: 'Available',
    transport: 'Paris Metro, RER, TGV trains, buses',
    emergencyPolice: '17',
    emergencyAmbulance: '15',
    emergencyFire: '18',
    vaccines: [],
    pakistaniCommunity: 'Moderate',
    internet: 'Excellent 4G/5G, WiFi in cafes and public spaces',
    description: 'Schengen country — Eiffel Tower, Louvre, French Riviera, and world-class cuisine.',
  },
  Germany: {
    languages: ['German', 'English'],
    dialCode: '+49',
    plugType: 'Type C/F',
    voltage: '230V',
    waterSafe: true,
    tipping: '5-10% at restaurants; round up taxi fares',
    halalFood: 'Available',
    transport: 'Deutsche Bahn, U-Bahn, S-Bahn, trams, buses',
    emergencyPolice: '110',
    emergencyAmbulance: '112',
    emergencyFire: '112',
    vaccines: [],
    pakistaniCommunity: 'Moderate',
    internet: 'Excellent coverage, WiFi in cities',
    description: 'Schengen country with strong economy, engineering excellence, and rich history. Popular for study and work.',
  },
  Greece: {
    languages: ['Greek', 'English'],
    dialCode: '+30',
    plugType: 'Type C/E/F',
    voltage: '230V',
    waterSafe: true,
    tipping: '5-10% at restaurants',
    halalFood: 'Limited',
    transport: 'Athens Metro, KTEL buses, taxis, ferries to islands',
    emergencyPolice: '100',
    emergencyAmbulance: '166',
    emergencyFire: '199',
    vaccines: [],
    pakistaniCommunity: 'Small',
    internet: 'Good coverage, WiFi in tourist areas',
    description: 'Schengen country with ancient ruins, Mediterranean islands, and stunning beaches.',
  },
  India: {
    languages: ['Hindi', 'English', 'Urdu', 'Tamil', 'Bengali'],
    dialCode: '+91',
    plugType: 'Type C/D',
    voltage: '230V',
    waterSafe: false,
    tipping: '10% at restaurants; small tips for services',
    halalFood: 'Widely Available',
    transport: 'Uber, Ola, auto-rickshaw, Indian Railways, metro',
    emergencyPolice: '112',
    emergencyAmbulance: '108',
    emergencyFire: '101',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Large',
    internet: 'Excellent 4G/5G, cheap data plans',
    description: 'Neighboring country with deep cultural and historical ties. Limited direct travel — check current political situation.',
  },
  Iran: {
    languages: ['Persian (Farsi)', 'English'],
    dialCode: '+98',
    plugType: 'Type C/F',
    voltage: '230V',
    waterSafe: false,
    tipping: 'Not customary in restaurants',
    halalFood: 'Widely Available',
    transport: 'Snapp (ride-hailing), taxis, metro in Tehran, buses',
    emergencyPolice: '110',
    emergencyAmbulance: '115',
    emergencyFire: '125',
    vaccines: [],
    pakistaniCommunity: 'Moderate',
    internet: '3G/4G; note: social media restricted — use VPN',
    description: 'Neighbor with deep cultural and religious ties. Visa-free for Pakistani pilgrims to holy sites in some cases.',
  },
  Iraq: {
    languages: ['Arabic', 'Kurdish', 'English'],
    dialCode: '+964',
    plugType: 'Type C/D/G',
    voltage: '230V',
    waterSafe: false,
    tipping: 'Not customary',
    halalFood: 'Widely Available',
    transport: 'Taxis, shared taxis, limited public transport',
    emergencyPolice: '104',
    emergencyAmbulance: '105',
    emergencyFire: '115',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Small',
    internet: '3G available, WiFi in hotels',
    description: 'Cradle of civilization with ancient Mesopotamian sites. Security situation varies by region — check advisories.',
  },
  Ireland: {
    languages: ['English', 'Irish'],
    dialCode: '+353',
    plugType: 'Type G',
    voltage: '230V',
    waterSafe: true,
    tipping: 'Not required; 10-15% for good service',
    halalFood: 'Available',
    transport: 'Dublin Bus, Luas tram, Irish Rail, taxis',
    emergencyPolice: '112',
    emergencyAmbulance: '112',
    emergencyFire: '112',
    vaccines: [],
    pakistaniCommunity: 'Small',
    internet: 'Good coverage, WiFi widely available',
    description: 'English-speaking EU country with friendly people, green landscapes, and growing tech sector.',
  },
  Italy: {
    languages: ['Italian', 'English'],
    dialCode: '+39',
    plugType: 'Type C/F/L',
    voltage: '230V',
    waterSafe: true,
    tipping: 'Not required — coperto (cover charge) usually added',
    halalFood: 'Available',
    transport: 'Trenitalia, metro (Rome/Milan), buses, vaporetti (Venice)',
    emergencyPolice: '113',
    emergencyAmbulance: '118',
    emergencyFire: '115',
    vaccines: [],
    pakistaniCommunity: 'Moderate',
    internet: 'Good 4G, WiFi in cities',
    description: 'Schengen country — Rome, Venice, Florence, and the Amalfi Coast. Pakistani diaspora is growing.',
  },
  Japan: {
    languages: ['Japanese', 'English'],
    dialCode: '+81',
    plugType: 'Type A/B',
    voltage: '100V',
    waterSafe: true,
    tipping: 'Not expected and may be refused',
    halalFood: 'Limited',
    transport: 'JR Rail, metro, buses, taxis',
    emergencyPolice: '110',
    emergencyAmbulance: '119',
    emergencyFire: '119',
    vaccines: [],
    pakistaniCommunity: 'Small',
    internet: 'Excellent coverage, WiFi in convenience stores and stations',
    description: 'Ultra-modern country with ancient temples, cherry blossoms, and world-class technology. Note: 100V voltage (different from Pakistan).',
  },
  Kuwait: {
    languages: ['Arabic', 'English'],
    dialCode: '+965',
    plugType: 'Type C/G',
    voltage: '240V',
    waterSafe: true,
    tipping: 'Not expected',
    halalFood: 'Widely Available',
    transport: 'Careem, taxis, buses',
    emergencyPolice: '112',
    emergencyAmbulance: '112',
    emergencyFire: '112',
    vaccines: [],
    pakistaniCommunity: 'Moderate',
    internet: 'Excellent 5G coverage',
    description: 'Gulf state with modern infrastructure, Kuwait Towers, and a large expatriate community.',
  },
  Lebanon: {
    languages: ['Arabic', 'French', 'English'],
    dialCode: '+961',
    plugType: 'Type A/B/C/D/G',
    voltage: '110V/220V',
    waterSafe: false,
    tipping: '10-15% at restaurants',
    halalFood: 'Widely Available',
    transport: 'Uber, Careem, taxis, shared service taxis',
    emergencyPolice: '112',
    emergencyAmbulance: '140',
    emergencyFire: '125',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Small',
    internet: 'Good 3G/4G, WiFi in hotels',
    description: 'Rich Phoenician history, delicious cuisine, and vibrant nightlife. Beirut is the "Paris of the Middle East."',
  },
  Luxembourg: {
    languages: ['Luxembourgish', 'French', 'German', 'English'],
    dialCode: '+352',
    plugType: 'Type C/F',
    voltage: '230V',
    waterSafe: true,
    tipping: 'Service included; small tip appreciated',
    halalFood: 'Available',
    transport: 'Buses, trains, free public transport nationwide',
    emergencyPolice: '113',
    emergencyAmbulance: '112',
    emergencyFire: '112',
    vaccines: [],
    pakistaniCommunity: 'Very Small',
    internet: 'Excellent coverage, WiFi widely available',
    description: 'Wealthy Schengen country with the highest GDP per capita. Free public transport is a bonus.',
  },
  Mexico: {
    languages: ['Spanish', 'English'],
    dialCode: '+52',
    plugType: 'Type A/B',
    voltage: '127V',
    waterSafe: false,
    tipping: '10-15% at restaurants is expected',
    halalFood: 'Limited',
    transport: 'Uber, buses, metro (Mexico City), domestic flights',
    emergencyPolice: '911',
    emergencyAmbulance: '911',
    emergencyFire: '911',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Very Small',
    internet: 'Good 4G in cities, WiFi in hotels',
    description: 'Vibrant Latin American culture, ancient Mayan ruins, and beautiful beaches.',
  },
  Mongolia: {
    languages: ['Mongolian', 'English'],
    dialCode: '+976',
    plugType: 'Type C/E/F',
    voltage: '230V',
    waterSafe: false,
    tipping: 'Not expected',
    halalFood: 'Limited',
    transport: 'Taxis, buses, domestic flights',
    emergencyPolice: '102',
    emergencyAmbulance: '103',
    emergencyFire: '101',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Very Small',
    internet: 'Limited coverage, WiFi in Ulaanbaatar hotels',
    description: 'Land of vast steppes, nomadic culture, and Genghis Khan heritage. Adventure destination for intrepid travelers.',
  },
  Morocco: {
    languages: ['Arabic', 'French', 'Berber', 'English'],
    dialCode: '+212',
    plugType: 'Type C/E',
    voltage: '220V',
    waterSafe: false,
    tipping: '10% at restaurants; small tips for guides',
    halalFood: 'Widely Available',
    transport: 'Grand taxis, petit taxis, CTM buses, trains',
    emergencyPolice: '19',
    emergencyAmbulance: '15',
    emergencyFire: '15',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Very Small',
    internet: 'Good 3G/4G, WiFi in hotels and riads',
    description: 'North African gem with Marrakech, Sahara Desert, and Fes medina. Muslim-friendly destination.',
  },
  Netherlands: {
    languages: ['Dutch', 'English'],
    dialCode: '+31',
    plugType: 'Type C/E',
    voltage: '230V',
    waterSafe: true,
    tipping: 'Not expected; 5-10% for good service',
    halalFood: 'Available',
    transport: 'NS trains, trams, buses, cycling everywhere',
    emergencyPolice: '112',
    emergencyAmbulance: '112',
    emergencyFire: '112',
    vaccines: [],
    pakistaniCommunity: 'Moderate',
    internet: 'Excellent coverage, WiFi widely available',
    description: 'Schengen country — tulips, windmills, Amsterdam canals, and a thriving Pakistani diaspora.',
  },
  NewZealand: {
    languages: ['English', 'Maori'],
    dialCode: '+64',
    plugType: 'Type I',
    voltage: '230V',
    waterSafe: true,
    tipping: 'Not expected',
    halalFood: 'Available',
    transport: 'Uber, buses, InterCity coaches, domestic flights',
    emergencyPolice: '111',
    emergencyAmbulance: '111',
    emergencyFire: '111',
    vaccines: [],
    pakistaniCommunity: 'Small',
    internet: 'Good coverage, WiFi in cities',
    description: 'Stunning natural beauty — Lord of the Rings landscapes, adventure sports, and peaceful lifestyle.',
  },
  Norway: {
    languages: ['Norwegian', 'English'],
    dialCode: '+47',
    plugType: 'Type C/F',
    voltage: '230V',
    waterSafe: true,
    tipping: 'Not expected — service charge included',
    halalFood: 'Available',
    transport: 'Ruter buses, T-bane (Oslo), Vy trains, ferries',
    emergencyPolice: '112',
    emergencyAmbulance: '113',
    emergencyFire: '110',
    vaccines: [],
    pakistaniCommunity: 'Moderate',
    internet: 'Excellent coverage, WiFi widely available',
    description: 'Schengen country with fjords, Northern Lights, and one of the world\'s highest living standards.',
  },
  Poland: {
    languages: ['Polish', 'English'],
    dialCode: '+48',
    plugType: 'Type C/E',
    voltage: '230V',
    waterSafe: true,
    tipping: '10% at restaurants',
    halalFood: 'Available',
    transport: 'PKP trains, buses, trams, metro (Warsaw)',
    emergencyPolice: '112',
    emergencyAmbulance: '112',
    emergencyFire: '112',
    vaccines: [],
    pakistaniCommunity: 'Small',
    internet: 'Good coverage, WiFi in cities',
    description: 'Affordable Schengen country with medieval cities, rich history, and growing economy.',
  },
  Portugal: {
    languages: ['Portuguese', 'English'],
    dialCode: '+351',
    plugType: 'Type C/F',
    voltage: '230V',
    waterSafe: true,
    tipping: '5-10% at restaurants',
    halalFood: 'Available',
    transport: 'Metro (Lisbon/Porto), trains, buses, trams',
    emergencyPolice: '112',
    emergencyAmbulance: '112',
    emergencyFire: '112',
    vaccines: [],
    pakistaniCommunity: 'Small',
    internet: 'Good coverage, WiFi widely available',
    description: 'Schengen country — sunny beaches, historic Lisbon, Port wine, and affordable living.',
  },
  Romania: {
    languages: ['Romanian', 'English'],
    dialCode: '+40',
    plugType: 'Type C/F',
    voltage: '230V',
    waterSafe: false,
    tipping: '10% at restaurants',
    halalFood: 'Limited',
    transport: 'Uber, Bolt, metro (Bucharest), CFR trains',
    emergencyPolice: '112',
    emergencyAmbulance: '112',
    emergencyFire: '112',
    vaccines: ['Hepatitis A'],
    pakistaniCommunity: 'Very Small',
    internet: 'Good 4G, WiFi in cities',
    description: 'Schengen country with Dracula\'s castle, Carpathian mountains, and affordable prices.',
  },
  Russia: {
    languages: ['Russian', 'English'],
    dialCode: '+7',
    plugType: 'Type C/F',
    voltage: '230V',
    waterSafe: false,
    tipping: '10-15% at restaurants is standard',
    halalFood: 'Available',
    transport: 'Moscow Metro, Yandex Go, trains, buses',
    emergencyPolice: '102',
    emergencyAmbulance: '103',
    emergencyFire: '101',
    vaccines: [],
    pakistaniCommunity: 'Small',
    internet: 'Good coverage in cities; WiFi available',
    description: 'World\'s largest country with rich history, Moscow\'s Red Square, and diverse landscapes.',
  },
  Singapore: {
    languages: ['English', 'Mandarin', 'Malay', 'Tamil'],
    dialCode: '+65',
    plugType: 'Type G',
    voltage: '230V',
    waterSafe: true,
    tipping: 'Not expected — 10% service charge included',
    halalFood: 'Widely Available',
    transport: 'MRT, buses, Grab, taxis',
    emergencyPolice: '999',
    emergencyAmbulance: '995',
    emergencyFire: '995',
    vaccines: [],
    pakistaniCommunity: 'Small',
    internet: 'Excellent 5G, free WiFi (Wireless@SG) everywhere',
    description: 'Modern city-state with Gardens by the Bay, Marina Bay Sands, and world-class food scene.',
  },
  SouthAfrica: {
    languages: ['English', 'Zulu', 'Xhosa', 'Afrikaans'],
    dialCode: '+27',
    plugType: 'Type C/D/M/N',
    voltage: '230V',
    waterSafe: false,
    tipping: '10-15% at restaurants',
    halalFood: 'Available',
    transport: 'Uber, Bolt, Gautrain, MyCiTi buses, minibus taxis',
    emergencyPolice: '10111',
    emergencyAmbulance: '10177',
    emergencyFire: '10177',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Small',
    internet: 'Good 4G, WiFi in cities and hotels',
    description: 'Rainbow Nation with Cape Town, Kruger National Park, and diverse culture.',
  },
  SouthKorea: {
    languages: ['Korean', 'English'],
    dialCode: '+82',
    plugType: 'Type C/F',
    voltage: '220V',
    waterSafe: true,
    tipping: 'Not expected and may be refused',
    halalFood: 'Available',
    transport: 'Seoul Metro, KTX trains, Kakao Taxis, buses',
    emergencyPolice: '112',
    emergencyAmbulance: '119',
    emergencyFire: '119',
    vaccines: [],
    pakistaniCommunity: 'Small',
    internet: 'World\'s fastest internet, free WiFi everywhere',
    description: 'K-pop, cutting-edge technology, ancient palaces, and Korean BBQ. Growing appeal for Pakistani tourists.',
  },
  Spain: {
    languages: ['Spanish', 'Catalan', 'English'],
    dialCode: '+34',
    plugType: 'Type C/F',
    voltage: '230V',
    waterSafe: true,
    tipping: 'Not required; small tip for good service',
    halalFood: 'Available',
    transport: 'Metro, Cercanías, AVE high-speed trains, buses',
    emergencyPolice: '092',
    emergencyAmbulance: '061',
    emergencyFire: '080',
    vaccines: [],
    pakistaniCommunity: 'Moderate',
    internet: 'Good 4G/5G, WiFi widely available',
    description: 'Schengen country — Barcelona, Madrid, Andalusia, and Mediterranean beaches.',
  },
  Sweden: {
    languages: ['Swedish', 'English'],
    dialCode: '+46',
    plugType: 'Type C/F',
    voltage: '230V',
    waterSafe: true,
    tipping: 'Not expected — service included',
    halalFood: 'Available',
    transport: 'SL (Stockholm), buses, Arlanda Express, SJ trains',
    emergencyPolice: '112',
    emergencyAmbulance: '112',
    emergencyFire: '112',
    vaccines: [],
    pakistaniCommunity: 'Moderate',
    internet: 'Excellent coverage, WiFi widely available',
    description: 'Schengen country with stunning nature, IKEA, Volvo, and a progressive society.',
  },
  Switzerland: {
    languages: ['German', 'French', 'Italian', 'English'],
    dialCode: '+41',
    plugType: 'Type C/J',
    voltage: '230V',
    waterSafe: true,
    tipping: 'Not required; 5% for good service',
    halalFood: 'Available',
    transport: 'SBB trains, trams, buses, boats',
    emergencyPolice: '117',
    emergencyAmbulance: '144',
    emergencyFire: '118',
    vaccines: [],
    pakistaniCommunity: 'Small',
    internet: 'Excellent coverage, WiFi in cities',
    description: 'Schengen country with Alps, lakes, luxury watches, and some of the world\'s highest living costs.',
  },
  Tunisia: {
    languages: ['Arabic', 'French', 'English'],
    dialCode: '+216',
    plugType: 'Type C/E',
    voltage: '230V',
    waterSafe: false,
    tipping: '10% at restaurants',
    halalFood: 'Widely Available',
    transport: 'Taxis, louages (shared taxis), trains, buses',
    emergencyPolice: '197',
    emergencyAmbulance: '190',
    emergencyFire: '198',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Very Small',
    internet: '3G/4G available, WiFi in hotels',
    description: 'North African country with Mediterranean beaches, ancient Carthage, and Star Wars filming locations.',
  },
  Turkmenistan: {
    languages: ['Turkmen', 'Russian', 'English'],
    dialCode: '+993',
    plugType: 'Type B/C/F',
    voltage: '220V',
    waterSafe: false,
    tipping: 'Not customary',
    halalFood: 'Widely Available',
    transport: 'Taxis, buses, domestic trains',
    emergencyPolice: '102',
    emergencyAmbulance: '103',
    emergencyFire: '101',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Very Small',
    internet: 'Limited coverage, WiFi in Ashgabat hotels',
    description: 'Central Asian nation with ancient Silk Road cities and the Darvaza Gas Crater (Door to Hell).',
  },
  UK: {
    languages: ['English'],
    dialCode: '+44',
    plugType: 'Type G',
    voltage: '230V',
    waterSafe: true,
    tipping: '10-15% at restaurants; not required at pubs',
    halalFood: 'Available',
    transport: 'Tube, buses, Uber, National Rail',
    emergencyPolice: '999',
    emergencyAmbulance: '999',
    emergencyFire: '999',
    vaccines: [],
    pakistaniCommunity: 'Large',
    internet: 'Excellent 5G, WiFi widely available',
    description: 'Top study and work destination. Large Pakistani diaspora in London, Manchester, Birmingham. Embassy visa takes 4-6 weeks.',
  },
  USA: {
    languages: ['English', 'Spanish'],
    dialCode: '+1',
    plugType: 'Type A/B',
    voltage: '120V',
    waterSafe: true,
    tipping: '15-20% at restaurants is expected',
    halalFood: 'Available',
    transport: 'Uber, Lyft, subways (NYC/Chicago), Amtrak',
    emergencyPolice: '911',
    emergencyAmbulance: '911',
    emergencyFire: '911',
    vaccines: [],
    pakistaniCommunity: 'Large',
    internet: 'Excellent 5G, WiFi widely available',
    description: 'World\'s largest economy. Popular for study, work, and family visits. Visa interview required — apply months in advance.',
  },
  Vietnam: {
    languages: ['Vietnamese', 'English'],
    dialCode: '+84',
    plugType: 'Type A/B/C',
    voltage: '220V',
    waterSafe: false,
    tipping: 'Not expected; 5-10% at upscale venues',
    halalFood: 'Limited',
    transport: 'Grab, xe om (motorbike taxis), buses, Vietnam Airlines domestic',
    emergencyPolice: '113',
    emergencyAmbulance: '115',
    emergencyFire: '114',
    vaccines: ['Hepatitis A', 'Typhoid'],
    pakistaniCommunity: 'Very Small',
    internet: 'Good 4G, WiFi in hotels and cafes',
    description: 'Affordable Southeast Asian gem with Ha Long Bay, ancient Hoi An, and vibrant street food culture.',
  },
};

export function getTravelInfo(code: string): TravelInfo {
  return COUNTRY_TRAVEL_INFO[code] || {
    languages: ['Local', 'English'],
    dialCode: '',
    plugType: 'Check locally',
    voltage: '220V',
    waterSafe: false,
    tipping: 'Check locally',
    halalFood: 'Limited',
    transport: 'Taxis, buses',
    emergencyPolice: '999',
    emergencyAmbulance: '998',
    emergencyFire: '997',
    vaccines: [],
    pakistaniCommunity: 'Very Small',
    internet: 'WiFi in hotels and cafes',
    description: 'Travel information for this destination is being researched. Verify details before your trip.',
  };
}
