'use client';

import React, { useState, useEffect, useRef, useCallback } from 'react';
import {
  FileText, BarChart3, MessageSquare,
  Send, Bot, User, Download, Printer,
  Sparkles, CheckCircle2, Star, Copy, Check, History, X,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { toast } from 'sonner';
import { useAppStore } from '@/lib/store';
import type { ChatMessage } from '@/lib/types';

interface ChatHistoryEntry {
  id: string;
  firstMessage: string;
  timestamp: string;
  messageCount: number;
}

const QUICK_PROMPTS = [
  'What documents do I need for UAE?',
  'Compare Turkey vs Malaysia visa',
  'Best visa-free destinations',
  'How to improve my visa score?',
];

function getChatHistory(): ChatHistoryEntry[] {
  if (typeof window === 'undefined') return [];
  try {
    const raw = localStorage.getItem('pakvisa-chat-history');
    if (!raw) return [];
    const parsed = JSON.parse(raw) as Array<{ id: string; messages: ChatMessage[]; timestamp: string }>;
    return parsed.slice(-5).reverse().map(entry => ({
      id: entry.id,
      firstMessage: entry.messages[0]?.content?.slice(0, 60) || 'New conversation',
      timestamp: entry.timestamp,
      messageCount: entry.messages.length,
    }));
  } catch {
    return [];
  }
}

function saveCurrentChatToHistory(messages: ChatMessage[]) {
  if (typeof window === 'undefined') return;
  if (messages.length < 2) return;
  try {
    const raw = localStorage.getItem('pakvisa-chat-history');
    const existing: Array<{ id: string; messages: ChatMessage[]; timestamp: string }> = raw ? JSON.parse(raw) : [];
    // Don't save if the last saved entry has the same first message
    const lastSaved = existing[existing.length - 1];
    if (lastSaved && lastSaved.messages[0]?.content === messages[0]?.content) {
      // Update existing entry
      lastSaved.messages = messages;
      lastSaved.timestamp = new Date().toISOString();
    } else {
      existing.push({
        id: Date.now().toString(),
        messages,
        timestamp: new Date().toISOString(),
      });
    }
    // Keep only last 10 conversations
    localStorage.setItem('pakvisa-chat-history', JSON.stringify(existing.slice(-10)));
  } catch {
    // Silently fail
  }
}

export function saveChatAs(messages: Array<{ role: 'user' | 'assistant'; content: string }>, format: 'txt' | 'pdf', title?: string) {
  const chatTitle = title || 'PakVisa Advisor - AI Chat';
  const dateStr = new Date().toLocaleString();

  if (format === 'txt') {
    const lines = [
      `${'='.repeat(50)}`,
      `  ${chatTitle}`,
      `  Exported: ${dateStr}`,
      `${'='.repeat(50)}`,
      '',
    ];
    messages.forEach((m, i) => {
      const label = m.role === 'user' ? '👤 You' : '🤖 Visa AI Assistant';
      lines.push(`[${label}]`);
      lines.push(m.content);
      lines.push('');
      if (i < messages.length - 1) lines.push('-'.repeat(40));
      lines.push('');
    });
    lines.push(`${'='.repeat(50)}`);
    lines.push('Generated by PakVisa Advisor — pakvisaadvisor.com');
    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `pakvisa-chat-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  } else {
    const printWindow = window.open('', '_blank', 'width=700,height=600');
    if (!printWindow) return;
    printWindow.document.write(`<!DOCTYPE html><html><head><title>${chatTitle}</title>
<style>
  body { font-family: 'Segoe UI', system-ui, sans-serif; max-width: 650px; margin: 0 auto; padding: 24px; color: #1a1a1a; font-size: 13px; line-height: 1.6; }
  h1 { font-size: 18px; text-align: center; color: #b45309; margin-bottom: 4px; }
  .meta { text-align: center; color: #666; font-size: 11px; margin-bottom: 20px; }
  .msg { margin-bottom: 14px; padding: 10px 12px; border-radius: 8px; page-break-inside: avoid; }
  .msg-user { background: #fff7ed; border-left: 3px solid #b45309; }
  .msg-bot { background: #f3f4f6; border-left: 3px solid #9ca3af; }
  .msg-label { font-weight: 600; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; color: #555; }
  .msg-content { white-space: pre-wrap; word-wrap: break-word; }
  .footer { text-align: center; margin-top: 24px; padding-top: 12px; border-top: 1px solid #ddd; font-size: 10px; color: #999; }
  @media print { body { padding: 12px; } }
</style></head><body>
  <h1>${chatTitle}</h1>
  <div class="meta">Exported on ${dateStr}</div>`);
    messages.forEach(m => {
      const cls = m.role === 'user' ? 'msg-user' : 'msg-bot';
      const label = m.role === 'user' ? 'You' : 'Visa AI Assistant';
      printWindow.document.write(`<div class="msg ${cls}"><div class="msg-label">${label}</div><div class="msg-content">${m.content.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div></div>`);
    });
    printWindow.document.write(`<div class="footer">Generated by PakVisa Advisor — pakvisaadvisor.com</div></body></html>`);
    printWindow.document.close();
    printWindow.onload = () => { printWindow.print(); };
  }
}

export function AIChatTab() {
  const { userProfile } = useAppStore();
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: '1', role: 'assistant', timestamp: new Date().toISOString(),
      content: 'Welcome to PakVisa AI Consultant! I can help you understand visa requirements, scoring, and application processes for Pakistani passport holders. Ask me about any country\'s visa rules, eligibility criteria, or application steps.',
    },
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [showHistory, setShowHistory] = useState(false);
  const [chatHistory, setChatHistory] = useState<ChatHistoryEntry[]>(() => getChatHistory());
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const historyRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, loading]);

  const refreshHistory = useCallback(() => {
    setChatHistory(getChatHistory());
  }, []);

  // Save to history when messages change (after a response)
  useEffect(() => {
    if (messages.length >= 2 && !loading) {
      const timer = setTimeout(() => saveCurrentChatToHistory(messages), 500);
      return () => clearTimeout(timer);
    }
  }, [messages.length, loading]);

  const handleCopy = async (content: string, msgId: string) => {
    try {
      await navigator.clipboard.writeText(content);
      setCopiedId(msgId);
      setTimeout(() => setCopiedId(null), 2000);
      toast.success('Copied to clipboard');
    } catch {
      toast.error('Failed to copy');
    }
  };

  const handleLoadHistory = (entry: ChatHistoryEntry) => {
    try {
      const raw = localStorage.getItem('pakvisa-chat-history');
      if (!raw) return;
      const parsed = JSON.parse(raw) as Array<{ id: string; messages: ChatMessage[]; timestamp: string }>;
      const found = parsed.find(e => e.id === entry.id);
      if (found) {
        setMessages(found.messages);
        setShowHistory(false);
        toast.success('Conversation loaded');
      }
    } catch {
      toast.error('Failed to load conversation');
    }
  };

  const sendMessage = async (msgOverride?: string) => {
    const messageText = msgOverride || input;
    if (!messageText.trim()) return;
    if (loading) return;
    const userMsg: ChatMessage = { id: Date.now().toString(), role: 'user', content: messageText, timestamp: new Date().toISOString() };
    setMessages(prev => [...prev, userMsg]);
    if (!msgOverride) setInput('');
    setLoading(true);

    try {
      const res = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: messageText, context: { profile: userProfile } }),
      });
      const data = await res.json();
      if (data.data) {
        setMessages(prev => [...prev, {
          id: (Date.now() + 1).toString(), role: 'assistant', content: data.data, timestamp: new Date().toISOString(),
        }]);
      } else {
        toast.error(data.error || 'Failed to get response');
      }
    } catch {
      toast.error('Network error. Please try again.');
    }
    setLoading(false);
  };

  return (
    <div className="flex flex-col h-[calc(100vh-280px)] min-h-[500px]">
      <Card className="mb-4 shrink-0 glass-card-strong">
        <CardContent className="p-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-amber-100 dark:bg-amber-900/40 flex items-center justify-center">
              <Bot className="w-5 h-5 text-amber-600" />
            </div>
            <div>
              <h3 className="font-semibold text-sm">AI Visa Consultant</h3>
              <p className="text-xs text-muted-foreground">Powered by AI · English only · Official sources cited</p>
            </div>
            <div className="ml-auto flex items-center gap-1.5">
              {/* History button */}
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="outline"
                      size="sm"
                      className="h-7 text-xs gap-1 relative"
                      onClick={() => { refreshHistory(); setShowHistory(!showHistory); }}
                    >
                      <History className="w-3 h-3" />
                      History
                      {chatHistory.length > 0 && (
                        <span className="absolute -top-1 -right-1 w-4 h-4 rounded-full bg-amber-500 text-white text-[9px] flex items-center justify-center font-bold">
                          {chatHistory.length}
                        </span>
                      )}
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent side="bottom" className="text-xs">View past conversations</TooltipContent>
                </Tooltip>
              </TooltipProvider>
              {messages.length > 1 && (
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        variant="outline"
                        size="sm"
                        className="h-7 text-xs gap-1"
                        onClick={() => saveChatAs(
                          messages.map(m => ({ role: m.role, content: m.content })),
                          'txt',
                          'PakVisa Advisor - AI Consultant Export'
                        )}
                      >
                        <Download className="w-3 h-3" />
                        Save .txt
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent side="bottom" className="text-xs">Download conversation as plain text</TooltipContent>
                  </Tooltip>
                </TooltipProvider>
              )}
              {messages.length > 1 && (
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        variant="outline"
                        size="sm"
                        className="h-7 text-xs gap-1"
                        onClick={() => saveChatAs(
                          messages.map(m => ({ role: m.role, content: m.content })),
                          'pdf',
                          'PakVisa Advisor - AI Consultant Export'
                        )}
                      >
                        <Printer className="w-3 h-3" />
                        Save PDF
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent side="bottom" className="text-xs">Print / Save as PDF</TooltipContent>
                  </Tooltip>
                </TooltipProvider>
              )}
              {userProfile && (
                <Badge variant="outline" className="text-xs">
                  <CheckCircle2 className="w-3 h-3 mr-1 text-amber-500" /> Profile Loaded
                </Badge>
              )}
            </div>
          </div>

          {/* Chat History Dropdown */}
          {showHistory && (
            <div ref={historyRef} className="mt-3 border rounded-lg bg-background p-2 space-y-1 max-h-60 overflow-y-auto custom-scrollbar-thin">
              {chatHistory.length === 0 ? (
                <p className="text-xs text-muted-foreground text-center py-4">No conversation history yet</p>
              ) : (
                chatHistory.map(entry => (
                  <button
                    key={entry.id}
                    onClick={() => handleLoadHistory(entry)}
                    className="w-full text-left px-3 py-2 rounded-md hover:bg-amber-50 dark:hover:bg-amber-900/20 transition-colors press-effect"
                  >
                    <p className="text-xs font-medium truncate">{entry.firstMessage}{entry.firstMessage.length >= 60 ? '...' : ''}</p>
                    <div className="flex items-center gap-2 mt-0.5">
                      <span className="text-[10px] text-muted-foreground">{new Date(entry.timestamp).toLocaleDateString()}</span>
                      <span className="text-[10px] text-muted-foreground">·</span>
                      <span className="text-[10px] text-muted-foreground">{entry.messageCount} messages</span>
                    </div>
                  </button>
                ))
              )}
              <div className="pt-1 border-t mt-1">
                <button
                  onClick={() => {
                    setMessages([{
                      id: Date.now().toString(), role: 'assistant', timestamp: new Date().toISOString(),
                      content: 'Welcome to PakVisa AI Consultant! I can help you understand visa requirements, scoring, and application processes for Pakistani passport holders.',
                    }]);
                    setShowHistory(false);
                  }}
                  className="w-full text-center px-3 py-1.5 rounded-md text-xs text-amber-600 dark:text-amber-400 hover:bg-amber-50 dark:hover:bg-amber-900/20 transition-colors font-medium press-effect"
                >
                  <Sparkles className="w-3 h-3 inline mr-1" />
                  Start New Conversation
                </button>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      <div className="flex-1 min-h-0 overflow-y-auto rounded-lg border p-4 custom-scrollbar-thin glass-card-strong">
        <div className="space-y-4">
          {messages.map(msg => (
            <div key={msg.id} className={`flex gap-3 ${msg.role === 'user' ? 'justify-end' : ''}`}>
              {msg.role === 'assistant' && (
                <div className="w-8 h-8 rounded-full bg-amber-100 dark:bg-amber-900/40 flex items-center justify-center shrink-0">
                  <Bot className="w-4 h-4 text-amber-600" />
                </div>
              )}
              <div className={`max-w-[80%] rounded-lg p-3 text-sm relative group ${
                msg.role === 'user'
                  ? 'chat-bubble-user'
                  : 'chat-bubble-bot'
              }`}>
                <p className="whitespace-pre-wrap">{msg.content}</p>
                <div className={`flex items-center gap-2 mt-1 ${msg.role === 'user' ? 'justify-end' : ''}`}>
                  <span className={`text-[10px] ${msg.role === 'user' ? 'text-amber-200' : 'text-muted-foreground'}`}>
                    {new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </span>
                  {msg.role === 'assistant' && msg.id !== '1' && (
                    <button
                      onClick={() => handleCopy(msg.content, msg.id)}
                      className="opacity-0 group-hover:opacity-100 transition-opacity p-0.5 rounded hover:bg-amber-100 dark:hover:bg-amber-900/30"
                      aria-label="Copy message"
                    >
                      {copiedId === msg.id ? (
                        <Check className="w-3 h-3 text-amber-500" />
                      ) : (
                        <Copy className="w-3 h-3 text-muted-foreground" />
                      )}
                    </button>
                  )}
                </div>
              </div>
              {msg.role === 'user' && (
                <div className="w-8 h-8 rounded-full bg-primary flex items-center justify-center shrink-0">
                  <User className="w-4 h-4 text-primary-foreground" />
                </div>
              )}
            </div>
          ))}
          {loading && (
            <div className="flex gap-3">
              <div className="w-8 h-8 rounded-full bg-amber-100 dark:bg-amber-900/40 flex items-center justify-center">
                <Bot className="w-4 h-4 text-amber-600 animate-pulse" />
              </div>
              <div className="chat-bubble-bot">
                <div className="chat-typing-indicator loading-dots"><span className="dot" /><span className="dot" /><span className="dot" /></div>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>
      </div>

      <div className="flex gap-2 mt-4 shrink-0 chat-input-container">
        <Input
          placeholder="Ask about visa requirements, eligibility, or application steps..."
          value={input}
          onChange={e => setInput(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && sendMessage()}
          className="flex-1 input-amber"
        />
        <Button onClick={() => sendMessage()} disabled={loading || !input.trim()} className="bg-amber-600 hover:bg-amber-700 relative z-10">
          <Send className="w-4 h-4" />
        </Button>
      </div>
      {/* Quick Prompts Bar */}
      <div className="flex flex-wrap gap-2 mt-3">
        {QUICK_PROMPTS.map((q) => (
          <button
            key={q}
            onClick={() => setInput(q)}
            className="quick-action-chip inline-flex items-center gap-1 px-3 py-1.5 rounded-full border border-amber-200 dark:border-amber-800 bg-amber-50 dark:bg-amber-900/10 text-amber-700 dark:text-amber-400 text-xs font-medium hover:bg-amber-100 dark:hover:bg-amber-900/20 transition-colors press-effect"
          >
            <Sparkles className="w-3 h-3" />
            {q.length > 35 ? q.substring(0, 35) + '...' : q}
          </button>
        ))}
      </div>
    </div>
  );
}
